### PR TITLE
Update/add bookshop data from herzbube bookhaul tour November 2024

### PR DESCRIPTION
**Pull request by herzbube**
I visited various bookstores in London between November 4-12 to flesh out my SciFi collection. Since the list you maintain was very helpful in some cases, it's only natural that I contribute to it. I uploaded a few more photos from the trip to Flickr than just the ones that I changed in the data file - in case you're interested you can find them in [this Flickr album](https://www.flickr.com/photos/herzbube/albums/72177720321925824).

### CODE REVIEW

**Comment by KakeLP** [comment]
Thank you for this! Unfortunately I have a bunch of updates locally that I haven’t been able to get onto GitHub, so I can’t apply this patch directly. I will see if I can figure out how to fix that problem, but it might take a while.

**Comment by KakeLP** [comment]
OK, I got "git push" working again and have pushed all the changes since my last push.

**Comment by herzbube** [comment]
Apologies for the delay. I've now merged your changes and fixed the conflicts, so the PR should now be clean again. Let me know if you have any questions.

**Comment by KakeLP** [comment]
Thank you! I’ve merged this and will update the site. Could you put the photos under a Creative Commons licence, please, so it’s clear that I have permission to use them?

**Comment by herzbube** [comment]
@KakeLP Done. I followed your example and used CC BY-NC-SA 2.0. Hope that's ok, otherwise just let me know.

**Comment by KakeLP** [comment]
That’s perfect, thanks! Everything is now live.

**Pull request merged**
